name: CD

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install -g esbuild
      - name: Run dnt
        run: deno task dnt
      - name: Run npm publish
        run: deno task npm-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
