name: Cloudflare Workers CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v4
        with:
          node-version: v20.x
      - run: |
          npm install -g esbuild
          deno task dnt
          deno task minify > test/runtimes/crystals-kyber.js
      - name: Run test
        working-directory: ./test/runtimes/cloudflare
        run: |
          npm install
          nohup npm start &
          sleep 3
          deno test crystals-kyber.spec.ts --allow-net
